// internal/proto/node.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: node.proto

package nodepb

import (
	commonpb "github.com/stevenmed26/AutoFarm/internal/proto/commonpb"
	simulationpb "github.com/stevenmed26/AutoFarm/internal/proto/simulationpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request from orchestrator to a single worker for a batch of ticks.
// We can use a streaming RPC for efficiency.
type WorkerTickRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SimulationId *commonpb.SimulationId `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	Tick         uint64                 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	// partition this worker is responsible for (e.g. "0/4")
	PartitionIndex uint32 `protobuf:"varint,3,opt,name=partition_index,json=partitionIndex,proto3" json:"partition_index,omitempty"`
	PartitionTotal uint32 `protobuf:"varint,4,opt,name=partition_total,json=partitionTotal,proto3" json:"partition_total,omitempty"`
	// subset of entities owned by this worker
	EntityIds     []uint64                       `protobuf:"varint,5,rep,packed,name=entity_ids,json=entityIds,proto3" json:"entity_ids,omitempty"`
	Config        *simulationpb.SimulationConfig `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerTickRequest) Reset() {
	*x = WorkerTickRequest{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerTickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerTickRequest) ProtoMessage() {}

func (x *WorkerTickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerTickRequest.ProtoReflect.Descriptor instead.
func (*WorkerTickRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerTickRequest) GetSimulationId() *commonpb.SimulationId {
	if x != nil {
		return x.SimulationId
	}
	return nil
}

func (x *WorkerTickRequest) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *WorkerTickRequest) GetPartitionIndex() uint32 {
	if x != nil {
		return x.PartitionIndex
	}
	return 0
}

func (x *WorkerTickRequest) GetPartitionTotal() uint32 {
	if x != nil {
		return x.PartitionTotal
	}
	return 0
}

func (x *WorkerTickRequest) GetEntityIds() []uint64 {
	if x != nil {
		return x.EntityIds
	}
	return nil
}

func (x *WorkerTickRequest) GetConfig() *simulationpb.SimulationConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// Response from worker with updated states for its partition.
type WorkerTickResponse struct {
	state        protoimpl.MessageState      `protogen:"open.v1"`
	SimulationId *commonpb.SimulationId      `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	Tick         uint64                      `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	Entities     []*simulationpb.EntityState `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"`
	// worker-local metrics
	ComputeMs     float64 `protobuf:"fixed64,4,opt,name=compute_ms,json=computeMs,proto3" json:"compute_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerTickResponse) Reset() {
	*x = WorkerTickResponse{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerTickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerTickResponse) ProtoMessage() {}

func (x *WorkerTickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerTickResponse.ProtoReflect.Descriptor instead.
func (*WorkerTickResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerTickResponse) GetSimulationId() *commonpb.SimulationId {
	if x != nil {
		return x.SimulationId
	}
	return nil
}

func (x *WorkerTickResponse) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *WorkerTickResponse) GetEntities() []*simulationpb.EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *WorkerTickResponse) GetComputeMs() float64 {
	if x != nil {
		return x.ComputeMs
	}
	return 0
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\rautofarm.node\x1a\x10simulation.proto\x1a\fcommon.proto\"\x9b\x02\n" +
	"\x11WorkerTickRequest\x12B\n" +
	"\rsimulation_id\x18\x01 \x01(\v2\x1d.autofarm.common.SimulationIdR\fsimulationId\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\x04R\x04tick\x12'\n" +
	"\x0fpartition_index\x18\x03 \x01(\rR\x0epartitionIndex\x12'\n" +
	"\x0fpartition_total\x18\x04 \x01(\rR\x0epartitionTotal\x12\x1d\n" +
	"\n" +
	"entity_ids\x18\x05 \x03(\x04R\tentityIds\x12=\n" +
	"\x06config\x18\x06 \x01(\v2%.autofarm.simulation.SimulationConfigR\x06config\"\xc9\x01\n" +
	"\x12WorkerTickResponse\x12B\n" +
	"\rsimulation_id\x18\x01 \x01(\v2\x1d.autofarm.common.SimulationIdR\fsimulationId\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\x04R\x04tick\x12<\n" +
	"\bentities\x18\x03 \x03(\v2 .autofarm.simulation.EntityStateR\bentities\x12\x1d\n" +
	"\n" +
	"compute_ms\x18\x04 \x01(\x01R\tcomputeMs2n\n" +
	"\x11NodeWorkerService\x12Y\n" +
	"\x0eRunWorkerTicks\x12 .autofarm.node.WorkerTickRequest\x1a!.autofarm.node.WorkerTickResponse(\x010\x01B7Z5github.com/stevenmed26/AutoFarm/internal/proto/nodepbb\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_node_proto_goTypes = []any{
	(*WorkerTickRequest)(nil),             // 0: autofarm.node.WorkerTickRequest
	(*WorkerTickResponse)(nil),            // 1: autofarm.node.WorkerTickResponse
	(*commonpb.SimulationId)(nil),         // 2: autofarm.common.SimulationId
	(*simulationpb.SimulationConfig)(nil), // 3: autofarm.simulation.SimulationConfig
	(*simulationpb.EntityState)(nil),      // 4: autofarm.simulation.EntityState
}
var file_node_proto_depIdxs = []int32{
	2, // 0: autofarm.node.WorkerTickRequest.simulation_id:type_name -> autofarm.common.SimulationId
	3, // 1: autofarm.node.WorkerTickRequest.config:type_name -> autofarm.simulation.SimulationConfig
	2, // 2: autofarm.node.WorkerTickResponse.simulation_id:type_name -> autofarm.common.SimulationId
	4, // 3: autofarm.node.WorkerTickResponse.entities:type_name -> autofarm.simulation.EntityState
	0, // 4: autofarm.node.NodeWorkerService.RunWorkerTicks:input_type -> autofarm.node.WorkerTickRequest
	1, // 5: autofarm.node.NodeWorkerService.RunWorkerTicks:output_type -> autofarm.node.WorkerTickResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
