// internal/proto/node.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: node.proto

package nodepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeWorkerService_RunWorkerTicks_FullMethodName = "/autofarm.node.NodeWorkerService/RunWorkerTicks"
)

// NodeWorkerServiceClient is the client API for NodeWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Node worker service
type NodeWorkerServiceClient interface {
	// Bi-directional streaming RPC:
	// Orchestrator streams WorkerTickRequest messages, worker responds with WorkerTickResponse messages.
	RunWorkerTicks(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerTickRequest, WorkerTickResponse], error)
}

type nodeWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeWorkerServiceClient(cc grpc.ClientConnInterface) NodeWorkerServiceClient {
	return &nodeWorkerServiceClient{cc}
}

func (c *nodeWorkerServiceClient) RunWorkerTicks(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerTickRequest, WorkerTickResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeWorkerService_ServiceDesc.Streams[0], NodeWorkerService_RunWorkerTicks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerTickRequest, WorkerTickResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeWorkerService_RunWorkerTicksClient = grpc.BidiStreamingClient[WorkerTickRequest, WorkerTickResponse]

// NodeWorkerServiceServer is the server API for NodeWorkerService service.
// All implementations must embed UnimplementedNodeWorkerServiceServer
// for forward compatibility.
//
// Node worker service
type NodeWorkerServiceServer interface {
	// Bi-directional streaming RPC:
	// Orchestrator streams WorkerTickRequest messages, worker responds with WorkerTickResponse messages.
	RunWorkerTicks(grpc.BidiStreamingServer[WorkerTickRequest, WorkerTickResponse]) error
	mustEmbedUnimplementedNodeWorkerServiceServer()
}

// UnimplementedNodeWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeWorkerServiceServer struct{}

func (UnimplementedNodeWorkerServiceServer) RunWorkerTicks(grpc.BidiStreamingServer[WorkerTickRequest, WorkerTickResponse]) error {
	return status.Errorf(codes.Unimplemented, "method RunWorkerTicks not implemented")
}
func (UnimplementedNodeWorkerServiceServer) mustEmbedUnimplementedNodeWorkerServiceServer() {}
func (UnimplementedNodeWorkerServiceServer) testEmbeddedByValue()                           {}

// UnsafeNodeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeWorkerServiceServer will
// result in compilation errors.
type UnsafeNodeWorkerServiceServer interface {
	mustEmbedUnimplementedNodeWorkerServiceServer()
}

func RegisterNodeWorkerServiceServer(s grpc.ServiceRegistrar, srv NodeWorkerServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeWorkerService_ServiceDesc, srv)
}

func _NodeWorkerService_RunWorkerTicks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeWorkerServiceServer).RunWorkerTicks(&grpc.GenericServerStream[WorkerTickRequest, WorkerTickResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeWorkerService_RunWorkerTicksServer = grpc.BidiStreamingServer[WorkerTickRequest, WorkerTickResponse]

// NodeWorkerService_ServiceDesc is the grpc.ServiceDesc for NodeWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autofarm.node.NodeWorkerService",
	HandlerType: (*NodeWorkerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunWorkerTicks",
			Handler:       _NodeWorkerService_RunWorkerTicks_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "node.proto",
}
