// internal/proto/common.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: common.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimulationStatus int32

const (
	SimulationStatus_SIMULATION_STATUS_UNSPECIFIED SimulationStatus = 0
	SimulationStatus_SIMULATION_STATUS_CREATED     SimulationStatus = 1
	SimulationStatus_SIMULATION_STATUS_RUNNING     SimulationStatus = 2
	SimulationStatus_SIMULATION_STATUS_PAUSED      SimulationStatus = 3
	SimulationStatus_SIMULATION_STATUS_COMPLETED   SimulationStatus = 4
	SimulationStatus_SIMULATION_STATUS_STOPPED     SimulationStatus = 5
	SimulationStatus_SIMULATION_STATUS_FAILED      SimulationStatus = 6
)

// Enum value maps for SimulationStatus.
var (
	SimulationStatus_name = map[int32]string{
		0: "SIMULATION_STATUS_UNSPECIFIED",
		1: "SIMULATION_STATUS_CREATED",
		2: "SIMULATION_STATUS_RUNNING",
		3: "SIMULATION_STATUS_PAUSED",
		4: "SIMULATION_STATUS_COMPLETED",
		5: "SIMULATION_STATUS_STOPPED",
		6: "SIMULATION_STATUS_FAILED",
	}
	SimulationStatus_value = map[string]int32{
		"SIMULATION_STATUS_UNSPECIFIED": 0,
		"SIMULATION_STATUS_CREATED":     1,
		"SIMULATION_STATUS_RUNNING":     2,
		"SIMULATION_STATUS_PAUSED":      3,
		"SIMULATION_STATUS_COMPLETED":   4,
		"SIMULATION_STATUS_STOPPED":     5,
		"SIMULATION_STATUS_FAILED":      6,
	}
)

func (x SimulationStatus) Enum() *SimulationStatus {
	p := new(SimulationStatus)
	*p = x
	return p
}

func (x SimulationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimulationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (SimulationStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x SimulationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimulationStatus.Descriptor instead.
func (SimulationStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type SimulationId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationId) Reset() {
	*x = SimulationId{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationId) ProtoMessage() {}

func (x *SimulationId) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationId.ProtoReflect.Descriptor instead.
func (*SimulationId) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *SimulationId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x0fautofarm.common\"$\n" +
	"\fSimulationId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value*\xef\x01\n" +
	"\x10SimulationStatus\x12!\n" +
	"\x1dSIMULATION_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SIMULATION_STATUS_CREATED\x10\x01\x12\x1d\n" +
	"\x19SIMULATION_STATUS_RUNNING\x10\x02\x12\x1c\n" +
	"\x18SIMULATION_STATUS_PAUSED\x10\x03\x12\x1f\n" +
	"\x1bSIMULATION_STATUS_COMPLETED\x10\x04\x12\x1d\n" +
	"\x19SIMULATION_STATUS_STOPPED\x10\x05\x12\x1c\n" +
	"\x18SIMULATION_STATUS_FAILED\x10\x06B9Z7github.com/stevenmed26/AutoFarm/internal/proto/commonpbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_proto_goTypes = []any{
	(SimulationStatus)(0), // 0: autofarm.common.SimulationStatus
	(*SimulationId)(nil),  // 1: autofarm.common.SimulationId
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
