// internal/proto/simulation.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: simulation.proto

package simulationpb

import (
	commonpb "github.com/stevenmed26/AutoFarm/internal/proto/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimulationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EntityCount   uint32                 `protobuf:"varint,2,opt,name=entity_count,json=entityCount,proto3" json:"entity_count,omitempty"`   // number of robots/agents
	TickRateMs    uint32                 `protobuf:"varint,3,opt,name=tick_rate_ms,json=tickRateMs,proto3" json:"tick_rate_ms,omitempty"`    // tick interval in milliseconds
	ScenarioType  string                 `protobuf:"bytes,4,opt,name=scenario_type,json=scenarioType,proto3" json:"scenario_type,omitempty"` // e.g. "harvest", "patrol", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationConfig) Reset() {
	*x = SimulationConfig{}
	mi := &file_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationConfig) ProtoMessage() {}

func (x *SimulationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationConfig.ProtoReflect.Descriptor instead.
func (*SimulationConfig) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *SimulationConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SimulationConfig) GetEntityCount() uint32 {
	if x != nil {
		return x.EntityCount
	}
	return 0
}

func (x *SimulationConfig) GetTickRateMs() uint32 {
	if x != nil {
		return x.TickRateMs
	}
	return 0
}

func (x *SimulationConfig) GetScenarioType() string {
	if x != nil {
		return x.ScenarioType
	}
	return ""
}

type Simulation struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            *commonpb.SimulationId    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Config        *SimulationConfig         `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Status        commonpb.SimulationStatus `protobuf:"varint,3,opt,name=status,proto3,enum=autofarm.common.SimulationStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp    `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp    `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp    `protobuf:"bytes,6,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Simulation) Reset() {
	*x = Simulation{}
	mi := &file_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Simulation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Simulation) ProtoMessage() {}

func (x *Simulation) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Simulation.ProtoReflect.Descriptor instead.
func (*Simulation) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *Simulation) GetId() *commonpb.SimulationId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Simulation) GetConfig() *SimulationConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Simulation) GetStatus() commonpb.SimulationStatus {
	if x != nil {
		return x.Status
	}
	return commonpb.SimulationStatus(0)
}

func (x *Simulation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Simulation) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Simulation) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

// Request to create a simulation (from API to Orchestrator)
type CreateSimulationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *SimulationConfig      `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSimulationRequest) Reset() {
	*x = CreateSimulationRequest{}
	mi := &file_simulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSimulationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSimulationRequest) ProtoMessage() {}

func (x *CreateSimulationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSimulationRequest.ProtoReflect.Descriptor instead.
func (*CreateSimulationRequest) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSimulationRequest) GetConfig() *SimulationConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateSimulationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Simulation    *Simulation            `protobuf:"bytes,1,opt,name=simulation,proto3" json:"simulation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSimulationResponse) Reset() {
	*x = CreateSimulationResponse{}
	mi := &file_simulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSimulationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSimulationResponse) ProtoMessage() {}

func (x *CreateSimulationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSimulationResponse.ProtoReflect.Descriptor instead.
func (*CreateSimulationResponse) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSimulationResponse) GetSimulation() *Simulation {
	if x != nil {
		return x.Simulation
	}
	return nil
}

// Lifecycle control
type StartSimulationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *commonpb.SimulationId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSimulationRequest) Reset() {
	*x = StartSimulationRequest{}
	mi := &file_simulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSimulationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSimulationRequest) ProtoMessage() {}

func (x *StartSimulationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSimulationRequest.ProtoReflect.Descriptor instead.
func (*StartSimulationRequest) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{4}
}

func (x *StartSimulationRequest) GetId() *commonpb.SimulationId {
	if x != nil {
		return x.Id
	}
	return nil
}

type StartSimulationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Simulation    *Simulation            `protobuf:"bytes,1,opt,name=simulation,proto3" json:"simulation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSimulationResponse) Reset() {
	*x = StartSimulationResponse{}
	mi := &file_simulation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSimulationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSimulationResponse) ProtoMessage() {}

func (x *StartSimulationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSimulationResponse.ProtoReflect.Descriptor instead.
func (*StartSimulationResponse) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{5}
}

func (x *StartSimulationResponse) GetSimulation() *Simulation {
	if x != nil {
		return x.Simulation
	}
	return nil
}

type StreamAggregatedTicksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *commonpb.SimulationId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAggregatedTicksRequest) Reset() {
	*x = StreamAggregatedTicksRequest{}
	mi := &file_simulation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAggregatedTicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAggregatedTicksRequest) ProtoMessage() {}

func (x *StreamAggregatedTicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAggregatedTicksRequest.ProtoReflect.Descriptor instead.
func (*StreamAggregatedTicksRequest) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{6}
}

func (x *StreamAggregatedTicksRequest) GetId() *commonpb.SimulationId {
	if x != nil {
		return x.Id
	}
	return nil
}

type PauseSimulationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *commonpb.SimulationId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseSimulationRequest) Reset() {
	*x = PauseSimulationRequest{}
	mi := &file_simulation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSimulationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSimulationRequest) ProtoMessage() {}

func (x *PauseSimulationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSimulationRequest.ProtoReflect.Descriptor instead.
func (*PauseSimulationRequest) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{7}
}

func (x *PauseSimulationRequest) GetId() *commonpb.SimulationId {
	if x != nil {
		return x.Id
	}
	return nil
}

type PauseSimulationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Simulation    *Simulation            `protobuf:"bytes,1,opt,name=simulation,proto3" json:"simulation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseSimulationResponse) Reset() {
	*x = PauseSimulationResponse{}
	mi := &file_simulation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSimulationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSimulationResponse) ProtoMessage() {}

func (x *PauseSimulationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSimulationResponse.ProtoReflect.Descriptor instead.
func (*PauseSimulationResponse) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{8}
}

func (x *PauseSimulationResponse) GetSimulation() *Simulation {
	if x != nil {
		return x.Simulation
	}
	return nil
}

type StopSimulationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *commonpb.SimulationId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSimulationRequest) Reset() {
	*x = StopSimulationRequest{}
	mi := &file_simulation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSimulationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSimulationRequest) ProtoMessage() {}

func (x *StopSimulationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSimulationRequest.ProtoReflect.Descriptor instead.
func (*StopSimulationRequest) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{9}
}

func (x *StopSimulationRequest) GetId() *commonpb.SimulationId {
	if x != nil {
		return x.Id
	}
	return nil
}

type StopSimulationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Simulation    *Simulation            `protobuf:"bytes,1,opt,name=simulation,proto3" json:"simulation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSimulationResponse) Reset() {
	*x = StopSimulationResponse{}
	mi := &file_simulation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSimulationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSimulationResponse) ProtoMessage() {}

func (x *StopSimulationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSimulationResponse.ProtoReflect.Descriptor instead.
func (*StopSimulationResponse) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{10}
}

func (x *StopSimulationResponse) GetSimulation() *Simulation {
	if x != nil {
		return x.Simulation
	}
	return nil
}

type GetSimulationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *commonpb.SimulationId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimulationRequest) Reset() {
	*x = GetSimulationRequest{}
	mi := &file_simulation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimulationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimulationRequest) ProtoMessage() {}

func (x *GetSimulationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimulationRequest.ProtoReflect.Descriptor instead.
func (*GetSimulationRequest) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{11}
}

func (x *GetSimulationRequest) GetId() *commonpb.SimulationId {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetSimulationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Simulation    *Simulation            `protobuf:"bytes,1,opt,name=simulation,proto3" json:"simulation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimulationResponse) Reset() {
	*x = GetSimulationResponse{}
	mi := &file_simulation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimulationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimulationResponse) ProtoMessage() {}

func (x *GetSimulationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimulationResponse.ProtoReflect.Descriptor instead.
func (*GetSimulationResponse) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{12}
}

func (x *GetSimulationResponse) GetSimulation() *Simulation {
	if x != nil {
		return x.Simulation
	}
	return nil
}

type EntityState struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	EntityId uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	// position
	X float64 `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	// velocity
	Vx float64 `protobuf:"fixed64,4,opt,name=vx,proto3" json:"vx,omitempty"`
	Vy float64 `protobuf:"fixed64,5,opt,name=vy,proto3" json:"vy,omitempty"`
	// battery/energy percentage (0–100)
	Battery float64 `protobuf:"fixed64,6,opt,name=battery,proto3" json:"battery,omitempty"`
	// opaque state, e.g. "idle", "moving", "working"
	Status        string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityState) Reset() {
	*x = EntityState{}
	mi := &file_simulation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityState) ProtoMessage() {}

func (x *EntityState) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityState.ProtoReflect.Descriptor instead.
func (*EntityState) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{13}
}

func (x *EntityState) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityState) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *EntityState) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *EntityState) GetVx() float64 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *EntityState) GetVy() float64 {
	if x != nil {
		return x.Vy
	}
	return 0
}

func (x *EntityState) GetBattery() float64 {
	if x != nil {
		return x.Battery
	}
	return 0
}

func (x *EntityState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// What the orchestrator sends to workers per tick
type SimulationTickRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SimulationId *commonpb.SimulationId `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	// monotonically increasing tick index
	Tick uint64 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	// subset of entity ids this worker should process
	EntityIds []uint64 `protobuf:"varint,3,rep,packed,name=entity_ids,json=entityIds,proto3" json:"entity_ids,omitempty"`
	// config snapshot for this simulation (duplicated for stateless workers)
	Config        *SimulationConfig      `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationTickRequest) Reset() {
	*x = SimulationTickRequest{}
	mi := &file_simulation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationTickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationTickRequest) ProtoMessage() {}

func (x *SimulationTickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationTickRequest.ProtoReflect.Descriptor instead.
func (*SimulationTickRequest) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{14}
}

func (x *SimulationTickRequest) GetSimulationId() *commonpb.SimulationId {
	if x != nil {
		return x.SimulationId
	}
	return nil
}

func (x *SimulationTickRequest) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *SimulationTickRequest) GetEntityIds() []uint64 {
	if x != nil {
		return x.EntityIds
	}
	return nil
}

func (x *SimulationTickRequest) GetConfig() *SimulationConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SimulationTickRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

// What workers send back to orchestrator
type SimulationTickResult struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SimulationId *commonpb.SimulationId `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	Tick         uint64                 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	// fully updated entity state for this worker's partition
	Entities []*EntityState `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"`
	// per-worker metrics
	ComputeMs     float64 `protobuf:"fixed64,4,opt,name=compute_ms,json=computeMs,proto3" json:"compute_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationTickResult) Reset() {
	*x = SimulationTickResult{}
	mi := &file_simulation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationTickResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationTickResult) ProtoMessage() {}

func (x *SimulationTickResult) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationTickResult.ProtoReflect.Descriptor instead.
func (*SimulationTickResult) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{15}
}

func (x *SimulationTickResult) GetSimulationId() *commonpb.SimulationId {
	if x != nil {
		return x.SimulationId
	}
	return nil
}

func (x *SimulationTickResult) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *SimulationTickResult) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SimulationTickResult) GetComputeMs() float64 {
	if x != nil {
		return x.ComputeMs
	}
	return 0
}

// Aggregated state that the orchestrator pushes toward the dashboard layer
type AggregatedTick struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SimulationId *commonpb.SimulationId `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	Tick         uint64                 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	Entities     []*EntityState         `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"`
	// simple metrics for the whole simulation at this tick
	AvgComputeMs  float64                `protobuf:"fixed64,4,opt,name=avg_compute_ms,json=avgComputeMs,proto3" json:"avg_compute_ms,omitempty"`
	WorkerCount   uint32                 `protobuf:"varint,5,opt,name=worker_count,json=workerCount,proto3" json:"worker_count,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedTick) Reset() {
	*x = AggregatedTick{}
	mi := &file_simulation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedTick) ProtoMessage() {}

func (x *AggregatedTick) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedTick.ProtoReflect.Descriptor instead.
func (*AggregatedTick) Descriptor() ([]byte, []int) {
	return file_simulation_proto_rawDescGZIP(), []int{16}
}

func (x *AggregatedTick) GetSimulationId() *commonpb.SimulationId {
	if x != nil {
		return x.SimulationId
	}
	return nil
}

func (x *AggregatedTick) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *AggregatedTick) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *AggregatedTick) GetAvgComputeMs() float64 {
	if x != nil {
		return x.AvgComputeMs
	}
	return 0
}

func (x *AggregatedTick) GetWorkerCount() uint32 {
	if x != nil {
		return x.WorkerCount
	}
	return 0
}

func (x *AggregatedTick) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_simulation_proto protoreflect.FileDescriptor

const file_simulation_proto_rawDesc = "" +
	"\n" +
	"\x10simulation.proto\x12\x13autofarm.simulation\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\x90\x01\n" +
	"\x10SimulationConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fentity_count\x18\x02 \x01(\rR\ventityCount\x12 \n" +
	"\ftick_rate_ms\x18\x03 \x01(\rR\n" +
	"tickRateMs\x12#\n" +
	"\rscenario_type\x18\x04 \x01(\tR\fscenarioType\"\xe2\x02\n" +
	"\n" +
	"Simulation\x12-\n" +
	"\x02id\x18\x01 \x01(\v2\x1d.autofarm.common.SimulationIdR\x02id\x12=\n" +
	"\x06config\x18\x02 \x01(\v2%.autofarm.simulation.SimulationConfigR\x06config\x129\n" +
	"\x06status\x18\x03 \x01(\x0e2!.autofarm.common.SimulationStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\"X\n" +
	"\x17CreateSimulationRequest\x12=\n" +
	"\x06config\x18\x01 \x01(\v2%.autofarm.simulation.SimulationConfigR\x06config\"[\n" +
	"\x18CreateSimulationResponse\x12?\n" +
	"\n" +
	"simulation\x18\x01 \x01(\v2\x1f.autofarm.simulation.SimulationR\n" +
	"simulation\"G\n" +
	"\x16StartSimulationRequest\x12-\n" +
	"\x02id\x18\x01 \x01(\v2\x1d.autofarm.common.SimulationIdR\x02id\"Z\n" +
	"\x17StartSimulationResponse\x12?\n" +
	"\n" +
	"simulation\x18\x01 \x01(\v2\x1f.autofarm.simulation.SimulationR\n" +
	"simulation\"M\n" +
	"\x1cStreamAggregatedTicksRequest\x12-\n" +
	"\x02id\x18\x01 \x01(\v2\x1d.autofarm.common.SimulationIdR\x02id\"G\n" +
	"\x16PauseSimulationRequest\x12-\n" +
	"\x02id\x18\x01 \x01(\v2\x1d.autofarm.common.SimulationIdR\x02id\"Z\n" +
	"\x17PauseSimulationResponse\x12?\n" +
	"\n" +
	"simulation\x18\x01 \x01(\v2\x1f.autofarm.simulation.SimulationR\n" +
	"simulation\"F\n" +
	"\x15StopSimulationRequest\x12-\n" +
	"\x02id\x18\x01 \x01(\v2\x1d.autofarm.common.SimulationIdR\x02id\"Y\n" +
	"\x16StopSimulationResponse\x12?\n" +
	"\n" +
	"simulation\x18\x01 \x01(\v2\x1f.autofarm.simulation.SimulationR\n" +
	"simulation\"E\n" +
	"\x14GetSimulationRequest\x12-\n" +
	"\x02id\x18\x01 \x01(\v2\x1d.autofarm.common.SimulationIdR\x02id\"X\n" +
	"\x15GetSimulationResponse\x12?\n" +
	"\n" +
	"simulation\x18\x01 \x01(\v2\x1f.autofarm.simulation.SimulationR\n" +
	"simulation\"\x98\x01\n" +
	"\vEntityState\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\x0e\n" +
	"\x02vx\x18\x04 \x01(\x01R\x02vx\x12\x0e\n" +
	"\x02vy\x18\x05 \x01(\x01R\x02vy\x12\x18\n" +
	"\abattery\x18\x06 \x01(\x01R\abattery\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\x8c\x02\n" +
	"\x15SimulationTickRequest\x12B\n" +
	"\rsimulation_id\x18\x01 \x01(\v2\x1d.autofarm.common.SimulationIdR\fsimulationId\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\x04R\x04tick\x12\x1d\n" +
	"\n" +
	"entity_ids\x18\x03 \x03(\x04R\tentityIds\x12=\n" +
	"\x06config\x18\x04 \x01(\v2%.autofarm.simulation.SimulationConfigR\x06config\x12=\n" +
	"\fscheduled_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\"\xcb\x01\n" +
	"\x14SimulationTickResult\x12B\n" +
	"\rsimulation_id\x18\x01 \x01(\v2\x1d.autofarm.common.SimulationIdR\fsimulationId\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\x04R\x04tick\x12<\n" +
	"\bentities\x18\x03 \x03(\v2 .autofarm.simulation.EntityStateR\bentities\x12\x1d\n" +
	"\n" +
	"compute_ms\x18\x04 \x01(\x01R\tcomputeMs\"\xae\x02\n" +
	"\x0eAggregatedTick\x12B\n" +
	"\rsimulation_id\x18\x01 \x01(\v2\x1d.autofarm.common.SimulationIdR\fsimulationId\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\x04R\x04tick\x12<\n" +
	"\bentities\x18\x03 \x03(\v2 .autofarm.simulation.EntityStateR\bentities\x12$\n" +
	"\x0eavg_compute_ms\x18\x04 \x01(\x01R\favgComputeMs\x12!\n" +
	"\fworker_count\x18\x05 \x01(\rR\vworkerCount\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt2\xa6\x05\n" +
	"\x11SimulationService\x12o\n" +
	"\x10CreateSimulation\x12,.autofarm.simulation.CreateSimulationRequest\x1a-.autofarm.simulation.CreateSimulationResponse\x12l\n" +
	"\x0fStartSimulation\x12+.autofarm.simulation.StartSimulationRequest\x1a,.autofarm.simulation.StartSimulationResponse\x12l\n" +
	"\x0fPauseSimulation\x12+.autofarm.simulation.PauseSimulationRequest\x1a,.autofarm.simulation.PauseSimulationResponse\x12i\n" +
	"\x0eStopSimulation\x12*.autofarm.simulation.StopSimulationRequest\x1a+.autofarm.simulation.StopSimulationResponse\x12f\n" +
	"\rGetSimulation\x12).autofarm.simulation.GetSimulationRequest\x1a*.autofarm.simulation.GetSimulationResponse\x12q\n" +
	"\x15StreamAggregatedTicks\x121.autofarm.simulation.StreamAggregatedTicksRequest\x1a#.autofarm.simulation.AggregatedTick0\x01B=Z;github.com/stevenmed26/AutoFarm/internal/proto/simulationpbb\x06proto3"

var (
	file_simulation_proto_rawDescOnce sync.Once
	file_simulation_proto_rawDescData []byte
)

func file_simulation_proto_rawDescGZIP() []byte {
	file_simulation_proto_rawDescOnce.Do(func() {
		file_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_simulation_proto_rawDesc), len(file_simulation_proto_rawDesc)))
	})
	return file_simulation_proto_rawDescData
}

var file_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_simulation_proto_goTypes = []any{
	(*SimulationConfig)(nil),             // 0: autofarm.simulation.SimulationConfig
	(*Simulation)(nil),                   // 1: autofarm.simulation.Simulation
	(*CreateSimulationRequest)(nil),      // 2: autofarm.simulation.CreateSimulationRequest
	(*CreateSimulationResponse)(nil),     // 3: autofarm.simulation.CreateSimulationResponse
	(*StartSimulationRequest)(nil),       // 4: autofarm.simulation.StartSimulationRequest
	(*StartSimulationResponse)(nil),      // 5: autofarm.simulation.StartSimulationResponse
	(*StreamAggregatedTicksRequest)(nil), // 6: autofarm.simulation.StreamAggregatedTicksRequest
	(*PauseSimulationRequest)(nil),       // 7: autofarm.simulation.PauseSimulationRequest
	(*PauseSimulationResponse)(nil),      // 8: autofarm.simulation.PauseSimulationResponse
	(*StopSimulationRequest)(nil),        // 9: autofarm.simulation.StopSimulationRequest
	(*StopSimulationResponse)(nil),       // 10: autofarm.simulation.StopSimulationResponse
	(*GetSimulationRequest)(nil),         // 11: autofarm.simulation.GetSimulationRequest
	(*GetSimulationResponse)(nil),        // 12: autofarm.simulation.GetSimulationResponse
	(*EntityState)(nil),                  // 13: autofarm.simulation.EntityState
	(*SimulationTickRequest)(nil),        // 14: autofarm.simulation.SimulationTickRequest
	(*SimulationTickResult)(nil),         // 15: autofarm.simulation.SimulationTickResult
	(*AggregatedTick)(nil),               // 16: autofarm.simulation.AggregatedTick
	(*commonpb.SimulationId)(nil),        // 17: autofarm.common.SimulationId
	(commonpb.SimulationStatus)(0),       // 18: autofarm.common.SimulationStatus
	(*timestamppb.Timestamp)(nil),        // 19: google.protobuf.Timestamp
}
var file_simulation_proto_depIdxs = []int32{
	17, // 0: autofarm.simulation.Simulation.id:type_name -> autofarm.common.SimulationId
	0,  // 1: autofarm.simulation.Simulation.config:type_name -> autofarm.simulation.SimulationConfig
	18, // 2: autofarm.simulation.Simulation.status:type_name -> autofarm.common.SimulationStatus
	19, // 3: autofarm.simulation.Simulation.created_at:type_name -> google.protobuf.Timestamp
	19, // 4: autofarm.simulation.Simulation.started_at:type_name -> google.protobuf.Timestamp
	19, // 5: autofarm.simulation.Simulation.ended_at:type_name -> google.protobuf.Timestamp
	0,  // 6: autofarm.simulation.CreateSimulationRequest.config:type_name -> autofarm.simulation.SimulationConfig
	1,  // 7: autofarm.simulation.CreateSimulationResponse.simulation:type_name -> autofarm.simulation.Simulation
	17, // 8: autofarm.simulation.StartSimulationRequest.id:type_name -> autofarm.common.SimulationId
	1,  // 9: autofarm.simulation.StartSimulationResponse.simulation:type_name -> autofarm.simulation.Simulation
	17, // 10: autofarm.simulation.StreamAggregatedTicksRequest.id:type_name -> autofarm.common.SimulationId
	17, // 11: autofarm.simulation.PauseSimulationRequest.id:type_name -> autofarm.common.SimulationId
	1,  // 12: autofarm.simulation.PauseSimulationResponse.simulation:type_name -> autofarm.simulation.Simulation
	17, // 13: autofarm.simulation.StopSimulationRequest.id:type_name -> autofarm.common.SimulationId
	1,  // 14: autofarm.simulation.StopSimulationResponse.simulation:type_name -> autofarm.simulation.Simulation
	17, // 15: autofarm.simulation.GetSimulationRequest.id:type_name -> autofarm.common.SimulationId
	1,  // 16: autofarm.simulation.GetSimulationResponse.simulation:type_name -> autofarm.simulation.Simulation
	17, // 17: autofarm.simulation.SimulationTickRequest.simulation_id:type_name -> autofarm.common.SimulationId
	0,  // 18: autofarm.simulation.SimulationTickRequest.config:type_name -> autofarm.simulation.SimulationConfig
	19, // 19: autofarm.simulation.SimulationTickRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	17, // 20: autofarm.simulation.SimulationTickResult.simulation_id:type_name -> autofarm.common.SimulationId
	13, // 21: autofarm.simulation.SimulationTickResult.entities:type_name -> autofarm.simulation.EntityState
	17, // 22: autofarm.simulation.AggregatedTick.simulation_id:type_name -> autofarm.common.SimulationId
	13, // 23: autofarm.simulation.AggregatedTick.entities:type_name -> autofarm.simulation.EntityState
	19, // 24: autofarm.simulation.AggregatedTick.completed_at:type_name -> google.protobuf.Timestamp
	2,  // 25: autofarm.simulation.SimulationService.CreateSimulation:input_type -> autofarm.simulation.CreateSimulationRequest
	4,  // 26: autofarm.simulation.SimulationService.StartSimulation:input_type -> autofarm.simulation.StartSimulationRequest
	7,  // 27: autofarm.simulation.SimulationService.PauseSimulation:input_type -> autofarm.simulation.PauseSimulationRequest
	9,  // 28: autofarm.simulation.SimulationService.StopSimulation:input_type -> autofarm.simulation.StopSimulationRequest
	11, // 29: autofarm.simulation.SimulationService.GetSimulation:input_type -> autofarm.simulation.GetSimulationRequest
	6,  // 30: autofarm.simulation.SimulationService.StreamAggregatedTicks:input_type -> autofarm.simulation.StreamAggregatedTicksRequest
	3,  // 31: autofarm.simulation.SimulationService.CreateSimulation:output_type -> autofarm.simulation.CreateSimulationResponse
	5,  // 32: autofarm.simulation.SimulationService.StartSimulation:output_type -> autofarm.simulation.StartSimulationResponse
	8,  // 33: autofarm.simulation.SimulationService.PauseSimulation:output_type -> autofarm.simulation.PauseSimulationResponse
	10, // 34: autofarm.simulation.SimulationService.StopSimulation:output_type -> autofarm.simulation.StopSimulationResponse
	12, // 35: autofarm.simulation.SimulationService.GetSimulation:output_type -> autofarm.simulation.GetSimulationResponse
	16, // 36: autofarm.simulation.SimulationService.StreamAggregatedTicks:output_type -> autofarm.simulation.AggregatedTick
	31, // [31:37] is the sub-list for method output_type
	25, // [25:31] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_simulation_proto_init() }
func file_simulation_proto_init() {
	if File_simulation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_simulation_proto_rawDesc), len(file_simulation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_simulation_proto_goTypes,
		DependencyIndexes: file_simulation_proto_depIdxs,
		MessageInfos:      file_simulation_proto_msgTypes,
	}.Build()
	File_simulation_proto = out.File
	file_simulation_proto_goTypes = nil
	file_simulation_proto_depIdxs = nil
}
