// internal/proto/simulation.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: simulation.proto

package simulationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SimulationService_CreateSimulation_FullMethodName      = "/autofarm.simulation.SimulationService/CreateSimulation"
	SimulationService_StartSimulation_FullMethodName       = "/autofarm.simulation.SimulationService/StartSimulation"
	SimulationService_PauseSimulation_FullMethodName       = "/autofarm.simulation.SimulationService/PauseSimulation"
	SimulationService_StopSimulation_FullMethodName        = "/autofarm.simulation.SimulationService/StopSimulation"
	SimulationService_GetSimulation_FullMethodName         = "/autofarm.simulation.SimulationService/GetSimulation"
	SimulationService_StreamAggregatedTicks_FullMethodName = "/autofarm.simulation.SimulationService/StreamAggregatedTicks"
)

// SimulationServiceClient is the client API for SimulationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RPC service exposed by the Orchestrator (called by API + maybe internal tools)
type SimulationServiceClient interface {
	CreateSimulation(ctx context.Context, in *CreateSimulationRequest, opts ...grpc.CallOption) (*CreateSimulationResponse, error)
	StartSimulation(ctx context.Context, in *StartSimulationRequest, opts ...grpc.CallOption) (*StartSimulationResponse, error)
	PauseSimulation(ctx context.Context, in *PauseSimulationRequest, opts ...grpc.CallOption) (*PauseSimulationResponse, error)
	StopSimulation(ctx context.Context, in *StopSimulationRequest, opts ...grpc.CallOption) (*StopSimulationResponse, error)
	GetSimulation(ctx context.Context, in *GetSimulationRequest, opts ...grpc.CallOption) (*GetSimulationResponse, error)
	StreamAggregatedTicks(ctx context.Context, in *StreamAggregatedTicksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AggregatedTick], error)
}

type simulationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulationServiceClient(cc grpc.ClientConnInterface) SimulationServiceClient {
	return &simulationServiceClient{cc}
}

func (c *simulationServiceClient) CreateSimulation(ctx context.Context, in *CreateSimulationRequest, opts ...grpc.CallOption) (*CreateSimulationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSimulationResponse)
	err := c.cc.Invoke(ctx, SimulationService_CreateSimulation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) StartSimulation(ctx context.Context, in *StartSimulationRequest, opts ...grpc.CallOption) (*StartSimulationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSimulationResponse)
	err := c.cc.Invoke(ctx, SimulationService_StartSimulation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) PauseSimulation(ctx context.Context, in *PauseSimulationRequest, opts ...grpc.CallOption) (*PauseSimulationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseSimulationResponse)
	err := c.cc.Invoke(ctx, SimulationService_PauseSimulation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) StopSimulation(ctx context.Context, in *StopSimulationRequest, opts ...grpc.CallOption) (*StopSimulationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopSimulationResponse)
	err := c.cc.Invoke(ctx, SimulationService_StopSimulation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) GetSimulation(ctx context.Context, in *GetSimulationRequest, opts ...grpc.CallOption) (*GetSimulationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSimulationResponse)
	err := c.cc.Invoke(ctx, SimulationService_GetSimulation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) StreamAggregatedTicks(ctx context.Context, in *StreamAggregatedTicksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AggregatedTick], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SimulationService_ServiceDesc.Streams[0], SimulationService_StreamAggregatedTicks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamAggregatedTicksRequest, AggregatedTick]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimulationService_StreamAggregatedTicksClient = grpc.ServerStreamingClient[AggregatedTick]

// SimulationServiceServer is the server API for SimulationService service.
// All implementations must embed UnimplementedSimulationServiceServer
// for forward compatibility.
//
// RPC service exposed by the Orchestrator (called by API + maybe internal tools)
type SimulationServiceServer interface {
	CreateSimulation(context.Context, *CreateSimulationRequest) (*CreateSimulationResponse, error)
	StartSimulation(context.Context, *StartSimulationRequest) (*StartSimulationResponse, error)
	PauseSimulation(context.Context, *PauseSimulationRequest) (*PauseSimulationResponse, error)
	StopSimulation(context.Context, *StopSimulationRequest) (*StopSimulationResponse, error)
	GetSimulation(context.Context, *GetSimulationRequest) (*GetSimulationResponse, error)
	StreamAggregatedTicks(*StreamAggregatedTicksRequest, grpc.ServerStreamingServer[AggregatedTick]) error
	mustEmbedUnimplementedSimulationServiceServer()
}

// UnimplementedSimulationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimulationServiceServer struct{}

func (UnimplementedSimulationServiceServer) CreateSimulation(context.Context, *CreateSimulationRequest) (*CreateSimulationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSimulation not implemented")
}
func (UnimplementedSimulationServiceServer) StartSimulation(context.Context, *StartSimulationRequest) (*StartSimulationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSimulation not implemented")
}
func (UnimplementedSimulationServiceServer) PauseSimulation(context.Context, *PauseSimulationRequest) (*PauseSimulationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseSimulation not implemented")
}
func (UnimplementedSimulationServiceServer) StopSimulation(context.Context, *StopSimulationRequest) (*StopSimulationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSimulation not implemented")
}
func (UnimplementedSimulationServiceServer) GetSimulation(context.Context, *GetSimulationRequest) (*GetSimulationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSimulation not implemented")
}
func (UnimplementedSimulationServiceServer) StreamAggregatedTicks(*StreamAggregatedTicksRequest, grpc.ServerStreamingServer[AggregatedTick]) error {
	return status.Errorf(codes.Unimplemented, "method StreamAggregatedTicks not implemented")
}
func (UnimplementedSimulationServiceServer) mustEmbedUnimplementedSimulationServiceServer() {}
func (UnimplementedSimulationServiceServer) testEmbeddedByValue()                           {}

// UnsafeSimulationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulationServiceServer will
// result in compilation errors.
type UnsafeSimulationServiceServer interface {
	mustEmbedUnimplementedSimulationServiceServer()
}

func RegisterSimulationServiceServer(s grpc.ServiceRegistrar, srv SimulationServiceServer) {
	// If the following call pancis, it indicates UnimplementedSimulationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SimulationService_ServiceDesc, srv)
}

func _SimulationService_CreateSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).CreateSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_CreateSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).CreateSimulation(ctx, req.(*CreateSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_StartSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).StartSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_StartSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).StartSimulation(ctx, req.(*StartSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_PauseSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).PauseSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_PauseSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).PauseSimulation(ctx, req.(*PauseSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_StopSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).StopSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_StopSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).StopSimulation(ctx, req.(*StopSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_GetSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).GetSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_GetSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).GetSimulation(ctx, req.(*GetSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_StreamAggregatedTicks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAggregatedTicksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SimulationServiceServer).StreamAggregatedTicks(m, &grpc.GenericServerStream[StreamAggregatedTicksRequest, AggregatedTick]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimulationService_StreamAggregatedTicksServer = grpc.ServerStreamingServer[AggregatedTick]

// SimulationService_ServiceDesc is the grpc.ServiceDesc for SimulationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimulationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autofarm.simulation.SimulationService",
	HandlerType: (*SimulationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSimulation",
			Handler:    _SimulationService_CreateSimulation_Handler,
		},
		{
			MethodName: "StartSimulation",
			Handler:    _SimulationService_StartSimulation_Handler,
		},
		{
			MethodName: "PauseSimulation",
			Handler:    _SimulationService_PauseSimulation_Handler,
		},
		{
			MethodName: "StopSimulation",
			Handler:    _SimulationService_StopSimulation_Handler,
		},
		{
			MethodName: "GetSimulation",
			Handler:    _SimulationService_GetSimulation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAggregatedTicks",
			Handler:       _SimulationService_StreamAggregatedTicks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "simulation.proto",
}
